### ISSUE TITLE
@XxParkerGamesxX  @caspervanneck resourcepacks

### ISSUE THREAD

**Issue by ondraczsk** [ImagicalMineReactive/ImagicalMine#10]
@caspervanneck and @XxParkerGamesxX resource packs is not working now, can u fix it?

**Comment by ghost** [comment]
@ondraczsk i cant realy help i hafe shool and i have a life so i am not always coding

**Comment by ghost** [comment]
and my own repo :P

**Comment by ghost** [comment]
if you wanth take some code from tere

**Comment by XxParkerGamesxX** [comment]
this has been fixed issue is now closed
