### ISSUE TITLE
What my host said when i wanted it added

### ISSUE THREAD

**Issue by XxParkerGamesxX** [ImagicalMineReactive/ImagicalMine#12]
Dear kevin
It doesn't seem to be working, and it doesn't even say which php version it needs so I can't add it yet.
Regards
Fade Host Support Team
Bernis

**Comment by ondraczsk** [comment]
?

**Comment by ondraczsk** [comment]
fix it

**Comment by XxParkerGamesxX** [comment]
fixed all good
