### ISSUE TITLE
Resourcepacks not work

### ISSUE THREAD

**Issue by ondraczsk** [ImagicalMineReactive/ImagicalMine#13]
@XxParkerGamesxX and @caspervanneck i test the resourcepacks and its not work

**Comment by ghost** [comment]
Yea and it will not work on any fork

**Comment by ghost** [comment]
On my fork or spoon it dont work

**Comment by ondraczsk** [comment]
hm

**Comment by ondraczsk** [comment]
do we need edit config? (to resourcepack) resource: true?

**Comment by ghost** [comment]
nope

**Comment by ghost** [comment]
it is not at player.php and resouchepack folder

**Comment by ondraczsk** [comment]
and server.php?

**Comment by ghost** [comment]
yes there to

**Comment by XxParkerGamesxX** [comment]
resource packs don't work on any software so there is no point
