### ISSUE TITLE
Is the PMANVIL better format than MCREGION?

### ISSUE THREAD

**Issue by ondraczsk** [ImagicalMineReactive/ImagicalMine#14]
@caspervanneck @XxParkerGamesxX I think mcregion is better, so i dont know if i can edit config to mcregion. Tell me your opinions

**Comment by ghost** [comment]
I use anvil not pmanvil

**Comment by ghost** [comment]
Most pc worlds use anvil

**Comment by ondraczsk** [comment]
ok
