### ISSUE TITLE
Tested?

### ISSUE THREAD

**Issue by XxParkerGamesxX** [ImagicalMineReactive/ImagicalMine#16]
Has anyone tested the software on a test server

**Comment by ondraczsk** [comment]
yea

**Comment by ondraczsk** [comment]
![bez nazvu](https://cloud.githubusercontent.com/assets/13401278/26410893/c99e1d2a-40a4-11e7-9f99-14fc89196cef.png)
good

**Comment by XxParkerGamesxX** [comment]
Do mobs work good

**Comment by ondraczsk** [comment]
i d k i didnt tested fully

**Comment by NFGamerMC** [comment]
Who cares

**Comment by NFGamerMC** [comment]
Also if you ban this account I have a lot of other dummy accounts
