### ISSUE TITLE
Command Block NOT WORK

### ISSUE THREAD

**Issue by ondraczsk** [ImagicalMineReactive/ImagicalMine#17]
when i want to give, it gives but it isnt nothing in inventory (inventory is empty)

**Comment by ghost** [comment]
:P

**Comment by ondraczsk** [comment]
?

**Comment by dries-c** [comment]
its not a bug because we are does not even add it :)

**Comment by ondraczsk** [comment]
:D so why is there CommandBlock.php
:D
