### ISSUE TITLE
This is illegal.

### ISSUE THREAD

**Issue by ghost** [ImagicalMineReactive/ImagicalMine#19]
IM is copyrighted I will file a LawSuit to GitHub

**Comment by ghost** [comment]
@NFGamerMC  i know that is why am not working on it

**Comment by XxParkerGamesxX** [comment]
You cannot file a lawsuit if you want to pay big bucks go right ahead

**Comment by ghost** [comment]
You are just a little kid so you clearly do not know a thing. Do you know that lawsuits do not cost money?

**Comment by XxParkerGamesxX** [comment]
Lol i'm 18 also a lawsuit does cost money so what your saying if you file a lawsuit there wouldnt be a court hearing i think there would you would need a lawyer now please gtfo of our software because you cant do shit

**Comment by ghost** [comment]
@NFGamerMC @XxParkerGamesxX why do guys efen talk if have noting nich to say then shut your mouth

**Comment by ghost** [comment]
@caspervanneck But Out!

**Comment by ghost** [comment]
@NFGamerMC what

**Comment by ghost** [comment]
???

**Comment by ghost** [comment]
@XxParkerGamesxX I can report this to GitHub and they will shut you down. This is your 5th time doing something illegal. Reminder: @caspervanneck Leave this chat.

**Comment by ghost** [comment]
okey
