### ISSUE TITLE
pls do not merge NFGamerMC

### ISSUE THREAD

**Issue by ondraczsk** [ImagicalMineReactive/ImagicalMine#22]
In circle ci says error

**Comment by ondraczsk** [comment]
thanks

**Comment by ghost** [comment]
fixt it );

**Comment by XxParkerGamesxX** [comment]
Ban nathan from this page wesley stop sticking up for the kid he can try and get me banned on github but he cant because i did nothing wrong

**Comment by ghost** [comment]
Hmm

**Comment by ghost** [comment]
Well I have 50 other people who are on my side

**Comment by ghost** [comment]
You cannot ban me as I have around 50 dummy accounts for people like you

**Comment by ghost** [comment]
i hate my self -_-

**Comment by ghost** [comment]
Why?

**Comment by ghost** [comment]
if need  ban am fine with it

**Comment by ondraczsk** [comment]
can i ban nfgamerMC?

**Comment by ghost** [comment]
I can explain

**Comment by ghost** [comment]
Just let me explain first

**Comment by ondraczsk** [comment]
ok

**Comment by ondraczsk** [comment]
explain it

**Comment by ghost** [comment]
What is your Discord, I don't want @XxParkerGamesxX to hear it

**Comment by ondraczsk** [comment]
ok wait, ill send you invitation

**Comment by ondraczsk** [comment]
connect: https://discord.gg/yYs4Ym

**Comment by ghost** [comment]
its for me not you @ondraczsk

**Comment by ondraczsk** [comment]
😄 ok

**Comment by ondraczsk** [comment]
but you can connect too it doesnt matter

**Comment by ghost** [comment]
@ondraczsk sorry for listening to .....

**Comment by ondraczsk** [comment]
@caspervanneck its for me not you
