### ISSUE TITLE
I am going to leave tish repo

### ISSUE THREAD

**Issue by ghost** [ImagicalMineReactive/ImagicalMine#23]
Because I have made to much trouble  so yea you can say somting nich and I mey stay

**Comment by ondraczsk** [comment]
trouble?

**Comment by ondraczsk** [comment]
you can stay, you didnt make trouble

**Comment by ondraczsk** [comment]
but one thing: is Bajan bad or good

**Comment by ondraczsk** [comment]
? @caspervanneck what do you think

**Comment by ghost** [comment]
What do think say you can let him here

**Comment by ondraczsk** [comment]
idk
