### ISSUE TITLE
Please use git and not the webeditor

### ISSUE THREAD

**Issue by dries-c** [ImagicalMineReactive/ImagicalMine#24]
### Issue description
Write a short description about the issue

### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ghost** [comment]
i use gitkraken @Driesboy  normal gesproken maar hier staat hij niet aan

**Comment by ondraczsk** [comment]
@caspervanneck holland?

**Comment by ghost** [comment]
@ondraczsk Yes am from holland

**Comment by dries-c** [comment]
dutch

**Comment by dries-c** [comment]
holland is a country

**Comment by buchwasa** [comment]
Use an IDE and git
