### ISSUE TITLE
Do u need help

### ISSUE THREAD

**Issue by XxParkerGamesxX** [ImagicalMineReactive/ImagicalMine#6]
### Issue description
Write a short description about the issue
I work for Rocky and GenisysPro and Tesseract if you need help contact me
### Steps to reproduce the issue

1...

2...

### OS and versions

* PHP:
* Server OS:
* Game version: 

### Crashdump, backtrace or other files

* ...

**Comment by ondraczsk** [comment]
ok i need :D if you want write here and i add you into team

**Comment by XxParkerGamesxX** [comment]
Alright thanks dude

**Comment by ondraczsk** [comment]
you have been invited

**Comment by XxParkerGamesxX** [comment]
I havent got the invite in my email yet

**Comment by ondraczsk** [comment]
look on https://github.com/orgs/ImagicalMineReactive/people and find the invitation on this web

**Comment by XxParkerGamesxX** [comment]
![screenshot_20170521-024230](https://cloud.githubusercontent.com/assets/22664407/26281768/2f905c0c-3dcf-11e7-9bf2-e878af169697.png)
Nothing there!

**Comment by ondraczsk** [comment]
look now

**Comment by XxParkerGamesxX** [comment]
Ok all good ty sir

**Comment by ondraczsk** [comment]
make some commit

**Comment by XxParkerGamesxX** [comment]
I will as you can see in the photo above its 2:40 am i gotta get some sleep

**Comment by ondraczsk** [comment]
at me is 8:50 :D

**Comment by XxParkerGamesxX** [comment]
Am or pm

**Comment by ondraczsk** [comment]
am

**Comment by XxParkerGamesxX** [comment]
What needs improvment

**Comment by XxParkerGamesxX** [comment]
Like what should i work on

**Comment by ondraczsk** [comment]
i dont know

**Comment by ondraczsk** [comment]
import some imagicalmine stuff

**Comment by XxParkerGamesxX** [comment]
Ok ill be sure to do that when i get up in 8hrs

**Comment by ondraczsk** [comment]
ok
