### ISSUE TITLE
@caspervanneck help

### ISSUE THREAD

**Issue by ondraczsk** [ImagicalMineReactive/ImagicalMine#8]
I need make customisable breakable bedrock with config, but it not works help pls @caspervanneck

**Comment by ghost** [comment]
yes i help

**Comment by ondraczsk** [comment]
hm look on bedrock block

**Comment by ondraczsk** [comment]
@caspervanneck do you know how to make bedrock breakable via config?

**Comment by ghost** [comment]
nope not realy and why do you need it if you build a spawn

**Comment by ondraczsk** [comment]
ok

**Comment by ondraczsk** [comment]
@caspervanneck we need to make something special in this im

**Comment by XxParkerGamesxX** [comment]
I can work something out

**Comment by XxParkerGamesxX** [comment]
ill see what I can do :)

**Comment by ondraczsk** [comment]
ok
