### ISSUE TITLE
No sound???

### ISSUE THREAD

**Issue by GkG0139** [ImagicalMineReactive/ImagicalMine#9]

**Comment by ondraczsk** [comment]
and what sound

**Comment by ondraczsk** [comment]
door sound or click sound? ..?

**Comment by ondraczsk** [comment]
and @G2PCraft what version of mcpe do you using?

**Comment by ondraczsk** [comment]
closing, reason:  at me sounds work

**Comment by GkG0139** [comment]
Sorry I'm using MCPE AntiLagg that make it no sound

**Comment by ondraczsk** [comment]
ah
